version: "3.7"
services:
  telearia:
    image: ghcr.io/besoeasy/telearia:main
    restart: unless-stopped
    ports:
      - "6799:6799"
      - "445:445"
    environment:
      TELEGRAMBOT: $APP_TELEGRAM_BOT_TOKEN
